{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "def test_failure():\n>       assert 1 == 3\nE       assert 1 == 3\n\ntest_demo.py:9: AssertionError"}, "start": 1726239035351, "stop": 1726239035351, "uuid": "98b804c9-8439-4d16-8909-2e54500e2565", "historyId": "d32927049f08b61feb937bc3b6dba9ad", "testCaseId": "d32927049f08b61feb937bc3b6dba9ad", "fullName": "test_demo#test_failure", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "host", "value": "LAPTOP-D366TVNA"}, {"name": "thread", "value": "10608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}